version: 2
jobs:
  build-publish-trigger:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build tested docker image
          command: ./build_test_tag_publish.sh

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
