version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            set -e
            ./pipe_build_up_test.sh
      - run:
          name: publish tagged docker image on dockerhub
          command: |
            set -e
            TAG_AND_PUBLISH=tag-and-publish-image.sh
            curl -O --fail https://raw.githubusercontent.com/cyber-dojo/cyber-dojo/master/dev/${TAG_AND_PUBLISH}
            chmod 700 ./${TAG_AND_PUBLISH}
            ./${TAG_AND_PUBLISH}
      - run:
          name: trigger dependent repos
          command: |
            set -e
            TRIGGER=trigger-dependent-repos.sh
            curl -O --fail https://raw.githubusercontent.com/cyber-dojo/cyber-dojo/master/dev/${TRIGGER}
            chmod 700 ./${TRIGGER}
            ./${TRIGGER} \
               "${CIRCLE_PROJECT_REPONAME}" \
               "${CIRCLE_SHA1}" \
                 web

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
