version: 2
jobs:
  build-publish-deploy:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Build tested docker image
          command: |
            # DOCKER_USER, DOCKER_PASS are in ci context
            echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
            ./build_test_publish.sh
            docker logout

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-publish-deploy:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
