version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build tested docker image
          command: |
            set -e
            ./pipe_build_up_test.sh
      - run:
          name: Tag docker image
          command: |
            set -e
            TAG=tag-image.sh
            curl -O --fail ${CIRCLECI_SCRIPT_DIR}/${TAG}
            chmod 700 ./${TAG}
            ./${TAG}
      - run:
          name: Publish tagged docker image on dockerhub
          command: |
            set -e
            PUBLISH=publish-tagged-image.sh
            curl -O --fail ${CIRCLECI_SCRIPT_DIR}/${PUBLISH}
            chmod 700 ./${PUBLISH}
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin            
            ./${PUBLISH}
      - run:
          name: Trigger dependent repos
          command: |
            set -e
            TRIGGER=trigger-dependent-repos.sh
            curl -O --fail ${CIRCLECI_SCRIPT_DIR}/${TRIGGER}
            chmod 700 ./${TRIGGER}
            ./${TRIGGER} web

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
